# Generated by Django 3.0.3 on 2020-02-17 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=120, null=True)),
                ('number_of_pages', models.IntegerField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=250, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_author_fk', to='books.Books')),
            ],
        ),
    ]
