# Generated by Django 3.0.3 on 2020-02-17 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='author',
            new_name='authors',
        ),
    ]
