# Generated by Django 3.0.3 on 2020-02-18 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200217_1535'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
